name: Cairo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cairo-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Scarb
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh
          export PATH=$PATH:~/.local/bin
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.scarb
            target
          key: ${{ runner.os }}-scarb-${{ hashFiles('**/Scarb.toml') }}
      
      - name: Run Cairo tests
        run: scarb test
      
      - name: Run Cairo format check
        run: scarb fmt --check