name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rust:
    name: Rust CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('merkle_tree_rust/Cargo.lock') }}

      - name: Check formatting
        run: cargo fmt --manifest-path merkle_tree_rust/Cargo.toml -- --check

      - name: Lint with clippy
        run: cargo clippy --manifest-path merkle_tree_rust/Cargo.toml -- -D warnings

      - name: Run tests
        run: cargo test --manifest-path merkle_tree_rust/Cargo.toml --verbose

      - name: Generate coverage
        run: |
          cargo install cargo-tarpaulin
          cargo tarpaulin --manifest-path merkle_tree_rust/Cargo.toml --out Xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3

  cairo:
    name: Cairo CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Scarb
        run: curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh | sh

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.scarb
          key: ${{ runner.os }}-scarb-${{ hashFiles('merkle_tree_cairo/Scarb.toml') }}

      - name: Run tests
        run: |
          cd merkle_tree_cairo
          scarb test

      - name: Run linter
        run: |
          cd merkle_tree_cairo
          scarb fmt --check